### ISSUE TITLE
Django-Appconf specifies 0.6

### ISSUE THREAD

**Issue by NSLockhart** [zyegfryed/django-statici18n#12]
Django-Appconf updated their code and released a 1.0 version.  Django-Statici18n requirements specifically states that django-appconf==0.6.  This would not allow users to update to django-appconf 1.0 without issues.

**Comment by zyegfryed** [comment]
Thanks for the feedback. Will have a look ASAP.
In the meantime, PR are welcome ;)

**Comment by zyegfryed** [comment]
Fixed in #13.
Closing the issue.
