### ISSUE TITLE
compilejsi18n command should skip system checks

### ISSUE THREAD

**Issue by bubenkoff** [zyegfryed/django-statici18n#14]
Otherwise it depends on database, which should not be the case for translations

**Comment by xolox** [comment]
It looks like all that's required is to add the class variable `requires_system_checks = False` to the management command `statici18n.management.commands.compilejsi18n.Command`.

**Comment by zyegfryed** [comment]
Thanks @bubenkoff and @xolox .
I've released v1.1.5 with the patch.

**Comment by bubenkoff** [comment]
thanks!
