### ISSUE TITLE
Django 1.9 / 1.10

### ISSUE THREAD

**Issue by liminspace** [zyegfryed/django-statici18n#18]
Please, add Django 1.9 and 1.10 support.
Under Django 1.9 there is warning: 
```
/django/core/management/__init__.py:345: RemovedInDjango110Warning: OptionParser usage for Django management commands is deprecated, use ArgumentParser instead
  self.fetch_command(subcommand).run_from_argv(self.argv)
```

In Django 1.10 will be error!

Or is this package dead and without support?

**Comment by julen** [comment]
[Django 1.10 is out](https://www.djangoproject.com/weblog/2016/aug/01/django-110-released/) so this has a higher priority now. @zyegfryed, would you be happy to make a new release provided there is a PR that handles this?

**Comment by zyegfryed** [comment]
Hi @julen ,
Yes, feel free to provide a PR.
I started some work on my side, but haven't completed it successfully – it looked easy to do, but was tricky at the end (maybe I'm a bit rusty). I can commit my code in a branch so you can finish it, or just get some inspiration.
If done within the day I can merge it and release it. Otherwise will have to wait a week or more since I'm going on holidays tomorrow.
Cheers!

**Comment by zyegfryed** [comment]
I've committed the code in [pr18](https://github.com/zyegfryed/django-statici18n/tree/pr18).
Warning: at this time of writing tests are broken.

**Comment by julen** [comment]
Thank you @zyegfryed. Checking that branch makes me wonder whether django-statici18n should drop explicit support for older Django versions. Note that as of today, only [1.8, 1.9 and 1.10 are officially supported](https://www.djangoproject.com/download/#supported-versions), which also affects [supported Python versions](https://docs.djangoproject.com/en/1.9/faq/install/#what-python-version-can-i-use-with-django). This would considerably reduce the tox matrix.

**Comment by zyegfryed** [comment]
Good point @julen . You're right and I think we should do the same, i.e. target the same Django and Python versions. Fell free to head this way and had a disclaimer in the documentation. This will definitely help with the maintenance headaches we have now.

**Comment by julen** [comment]
@zyegfryed cool, I'll prepare a PR that drops support for older Django/Python versions first and add a note in the docs/README.

By the way, I also checked [the branch you shared earlier](https://github.com/zyegfryed/django-statici18n/tree/pr18) and it seems like you have a couple of commits there which could directly go to master without further due.

**Comment by zyegfryed** [comment]
Yes, you're right. I'll try to commit them today. Thanks.

**Comment by julen** [comment]
I have opened #22 addressing this issue. I hope that's fine!
