### ISSUE TITLE
Support `USE_I18N = False`

### ISSUE THREAD

**Issue by julen** [zyegfryed/django-statici18n#19]
Hi there! This might initially sound a bit of an unusual request, so here's the context:

We have a web application which using django-statici18n, generates the JS locale files at the same location we set in `STATICFILES_DIRS`. This builds the JS files for all locales, and then `collectstatic` moves them over to our `STATIC_ROOT`. So far, so good.

Now here's the trick. The web application can be deployed by individuals at their own will, which also means `USE_I18N = False` is a valid scenario. Under these circumstances, running `compilejsi18n` builds files for **all locales**, even if only `settings.LANGUAGE_CODE` will always be used. At the same time, if run in conjunction with `collectstatic`, a lot of unnecessary files will be copied over to the static files serving location.

One can always manually pass a `-l <code>` flag, however as far as I see, supporting this use-case would be a trivial 2-line change in the management command and it would work transparently. So I wonder whether you would be up to accepting a PR for it?

Thanks in advance!

**Comment by zyegfryed** [comment]
Hi @julen ,
if I understand correctly, setting `USE_I18N` to `False` should to nothing, i.e. not generate any files. Is that it?
If so, feel free to send a PR with test and documentation and I'll merge it.
Thanks in advance.

**Comment by julen** [comment]
With `USE_I18N = False`, it should generate `en-us` files (provided this is the default, but it might be safer to use `settings.LANGUAGE_CODE`), because the application code still relies on `gettext()`, `ngettext()` etc. to be available. If you are ok with it, I'll PR the change.
