### ISSUE TITLE
Release new version for Django 1.10

### ISSUE THREAD

**Issue by mikicz** [zyegfryed/django-statici18n#24]
Hi, I see somebody has implemented the support for Django >= 1.8, however, new version still hasn't been released. Could you please give me a time frame of sorts when a new version is gonna be released? I am willing to help with any coding required to release as soon as possible...

**Comment by zyegfryed** [comment]
Hi @mikicz 
The idea is to release a new version ASAP. To do so, we need some help on 2 PRs: #23 and #17 to add tests and documentation. Feel free to jump on board and tackle them!
Once those 2 PRs are merged, a release will follow quickly.
Cheers

**Comment by zyegfryed** [comment]
Fixed in [ff02d1b5094dc18c8ae50518ad69a65f068a00e3].
