### ISSUE TITLE
Add version hash to url

### ISSUE THREAD

**Issue by liminspace** [zyegfryed/django-statici18n#25]
Hi!
There is a problem when a browser cache old js-file with translation. A good way is adding unique ending to url, for example `?v=hash`.
I implemented this case as a templatetag:

``` python
# coding=utf-8
from __future__ import absolute_import
import os
import hashlib
from django import template
from django.conf import settings
from unipath import Path
from django.contrib.staticfiles.templatetags.staticfiles import static
from statici18n.conf import settings as statici18n_settings
from statici18n.utils import get_filename

register = template.Library()

_JSI18N_URL_CACHE = {}

@register.simple_tag
def get_jsi18n_url(locale):
    url = _JSI18N_URL_CACHE.get(locale)
    if url is None:
        path = os.path.join(statici18n_settings.STATICI18N_OUTPUT_DIR,
                            get_filename(locale, statici18n_settings.STATICI18N_DOMAIN))
        try:
            mod_hash = hashlib.sha1(
                str(Path(settings.STATIC_ROOT, path).mtime())
            ).digest().encode('base64').replace('+', '').replace('/', '')[:8]
        except OSError:
            mod_hash = '0'
        url = static(path) + '?v=' + mod_hash
        _JSI18N_URL_CACHE[locale] = url
    return url
```

and use it in templates:

```
    {% if debug %}
        <script src="{% url 'jsi18n_catalog' %}"></script>
    {% else %}
        <script src="{% get_jsi18n_url LANGUAGE_CODE %}"></script>
    {% endif %}
```

I propose add similar implementation to your package because it is useful.

**Comment by zyegfryed** [comment]
Hi @liminspace ,
Did you try to [configure `staticfiles` support with `django-statici18n`](https://django-statici18n.readthedocs.io/en/latest/faq.html#how-to-configure-static-files-with-django-statici18n) ? You should then be able to leverage cache busting feature from `staticfiles` without modifying `django-statici18n`.
In case I'm missing the point there, feel free to detail your use case.
Cheers

**Comment by liminspace** [comment]
I talk about cache in browser. Not in server-side. In your solution url is the same for browser and browser don't update file because use it from cache even after the file has changed.

**Comment by zyegfryed** [comment]
Not if you're using [`django.contrib.staticfiles.storage.ManifestStaticFilesStorage`](https://docs.djangoproject.com/en/1.10/ref/contrib/staticfiles/#django.contrib.staticfiles.storage.ManifestStaticFilesStorage) for serving your files.

**Comment by zyegfryed** [comment]
Closing since no answer. Feel free to reopen the issue in any case.
