### ISSUE TITLE
Where did version 1.3.0 come from and what are the changes?

### ISSUE THREAD

**Issue by dwaynebailey** [zyegfryed/django-statici18n#30]
Version 1.3.0 is available from https://pypi.python.org/pypi/django-statici18n/1.3.0
But:

* There is no 1.3.0 in https://github.com/zyegfryed/django-statici18n/blob/master/docs/changelog.rst
* The github releases only go to 1.1.5 https://github.com/zyegfryed/django-statici18n/releases
* master is on v1.2.1 https://github.com/zyegfryed/django-statici18n/blob/master/src/statici18n/__init__.py#L2

**Comment by zyegfryed** [comment]
Fixed in [060dc83].
Thanks @dwaynebailey for point it out 🍰
