### ISSUE TITLE
Getting bytes as a translated chars

### ISSUE THREAD

**Issue by hemantbadhe** [zyegfryed/django-statici18n#46]
I am using this(in python 2.7) for implementing internationalization in XBlock for Open EDX project. It works fine but the issue is in pdf generation the translated English text to Marathi is not working.
suppose you have English char like "I" and the corresponding Marathi translation is "मी ", but in pdf, it gives like "\u092e\u0940".

Please help!

**Comment by zyegfryed** [comment]
Hi @hemantbadhe, can you please provide some code to see how this library is used in your context (PDF generation) to help me understand what's at stake?

**Comment by zyegfryed** [comment]
Up!

**Comment by zyegfryed** [comment]
Closing as stalled. Please, feel free to re-open the issue whether your still experiencing some trouble.
